In [1]:
import json
from pathlib import Path
import polars as pl
from IPython.display import Markdown
from polars import DataFrame, LazyFrame

In [2]:
from pan26_genai_detection.evaluator.evaluator import c_at_1, auc, f1, f05u, brier_score

def evaluate_all(y_true: pl.DataFrame, y_pred: pl.DataFrame):
    y_true = y_true.to_numpy()
    y_pred = y_pred.to_numpy()
    return pl.from_dict({
        'roc-auc': auc(y_true, y_pred),
        'brier': brier_score(y_true, y_pred),
        'c@1': c_at_1(y_true, y_pred),
        'f1': f1(y_true, y_pred),
        'f05u': f05u(y_true, y_pred),
    }).with_columns(
        pl.mean_horizontal(pl.all()).alias('mean'),
        pl.lit((y_pred[y_true == 0] >= 0.5).sum() / (y_true == 0).sum()).alias('fpr'),
        pl.lit((y_pred[y_true == 1] < 0.5).sum() / (y_true == 1).sum()).alias('fnr'),
    )

In [3]:
def build_truth_map(truth_file: Path, id_map_file: Path = None):
    truth_df = pl.read_ndjson(truth_file)
    if not id_map_file:
        return truth_df.with_columns(pl.lit(None).alias('orig_id'))
    id_map_df = pl.read_ndjson(id_map_file)
    return truth_df.join(id_map_df, on='id', how='left')

def load_run_files(rundir: Path):
    meta_df = pl.read_ndjson(rundir / 'metadata.jsonl')
    runs_df = []
    run_ids = meta_df.select('run_id').unique().to_series()

    # Leave no stray runs behind
    assert len(run_ids) == len(list(rundir.joinpath('outputs-flat').glob('2026-*')))

    for rid in run_ids:
        runfile = rundir / 'outputs-flat' / rid
        for l in runfile.open('r'):
            j = json.loads(l)
            j['run_id'] = rid
            runs_df.append(j)

    df = pl.from_records(runs_df)
    df = df.join(meta_df.select(['run_id', 'team', 'software', 'dataset']), on='run_id', how='left')
    return df

def join_runs_and_truth(runs_df: pl.DataFrame, meta_df: pl.DataFrame):
    df = runs_df.join(meta_df, on='id', how='left')
    df = df.rename({'label': 'label_pred', 'label_right': 'label_truth'})

    # Sanity check
    assert df['label_truth'].is_not_null().all()
    assert df['label_pred'].is_not_null().all()

    # Reorder columns and sort
    col_order = ['team', 'software', 'run_id', 'id', 'orig_id', 'model', 'source', 'label_pred', 'label_truth', 'dataset']
    df = df.select(col_order)
    df = df.sort(by=['team', 'software', 'run_id', 'model', 'label_truth'])
    return df

def load_run_truth_and_meta(base_path: Path, truth_file: Path, id_map_file: Path | None = None):
    truth_map_pan26 = build_truth_map(truth_file, id_map_file)
    runs_pan26 = load_run_files(base_path)
    return join_runs_and_truth(runs_pan26, truth_map_pan26)

In [4]:
BASE_PATH = Path('../data')
BASE_EVAL_PATH = BASE_PATH / 'task-eval'
BASE_RUN_PATH = BASE_EVAL_PATH / 'tira-runs'

In [5]:
pan25_df = load_run_truth_and_meta(BASE_RUN_PATH / 'pan25',
                                   BASE_PATH / 'splits' / 'pan25-voight-kampff-test-truth.jsonl')
pan25_df

shape: (758_661, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team      ┆ software  ┆ run_id    ┆ id        ┆ … ┆ source    ┆ label_pre ┆ label_tru ┆ dataset  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ d         ┆ th        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 9c4d7515- ┆ … ┆ riddell-j ┆ 0.721133  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ 347d-52df ┆   ┆ uola-o1-d ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b18f-60e ┆   ┆ eepseek   ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 2b4…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 85ee111e- ┆ … ┆ riddell-j ┆ 0.719153  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ 7793-561d ┆   ┆ uola-o1-d ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -adeb-c60 ┆   ┆ eepseek   ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 05d…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ d28287f4- ┆ … ┆ brennan-g ┆ 0.72062   ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ 4b7c-5e40 ┆   ┆ reenstadt ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -86fc-d80 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 048…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 8116d325- ┆ … ┆ riddell-j ┆ 0.721147  ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ 14ce-51f5 ┆   ┆ uola-o1-d ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -a8a8-e81 ┆   ┆ eepseek   ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 54a…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 914875d8- ┆ … ┆ brennan-g ┆ 0.72212   ┆ 1         ┆ pan25-ge │
│ tion      ┆ erg       ┆ 2-05-17-1 ┆ dbbb-506a ┆   ┆ reenstadt ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -8af6-127 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 01d…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 025b0308- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ dffc-5192 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -9fbc-63e ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ e2f…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ cd7f6528- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ aa55-5481 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -b16b-98a ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 2dd…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 25f67501- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 5396-5d44 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -9681-921 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 803…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 8e05b5ac- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 2878-5b61 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -ba9a-713 ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 1a6…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-1 ┆ 30c34c83- ┆ … ┆ pan24-tes ┆ 0.999997  ┆ 1         ┆ pan25-ge │
│ zeng      ┆           ┆ 0-22-08-3 ┆ 622d-5ea0 ┆   ┆ t         ┆           ┆           ┆ nerative │
│           ┆           ┆ 1         ┆ -8fad-79b ┆   ┆           ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 7e8…      ┆   ┆           ┆           ┆           ┆ ction-…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
pan26_df = load_run_truth_and_meta(BASE_RUN_PATH / 'pan26',
                                   BASE_PATH / 'splits' / 'pan26-voight-kampff-test-truth.jsonl',
                                   BASE_PATH / 'sampled' / 'pan26-voight-kampff-orig-ids.jsonl')
pan26_df

shape: (310_618, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team      ┆ software  ┆ run_id    ┆ id        ┆ … ┆ source    ┆ label_pre ┆ label_tru ┆ dataset  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ d         ┆ th        ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ a6d5ce11- ┆ … ┆ nytimes-w ┆ 0.719311  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 948f-5935 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -9319-ee4 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 509…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 233b35a4- ┆ … ┆ nytimes-w ┆ 0.721067  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 986f-512b ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -8152-b09 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ bb5…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 7b7b16a5- ┆ … ┆ nytimes-w ┆ 0.721603  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 27a2-572a ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -a6c6-8a9 ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 20d…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ 51ce6717- ┆ … ┆ nytimes-w ┆ 0.719695  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 03c0-5a37 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -ba2e-95f ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 17a…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ a-a-detec ┆ navy-iceb ┆ 2026-05-2 ┆ a2335f76- ┆ … ┆ nytimes-w ┆ 0.718517  ┆ 1         ┆ pan26-ge │
│ tion      ┆ erg       ┆ 2-00-36-0 ┆ 1cc4-59e7 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 5         ┆ -8efb-d7c ┆   ┆ ompts     ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 49d…      ┆   ┆           ┆           ┆           ┆ ction-…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ 5a5bfc46- ┆ … ┆ nytimes-w ┆ 0.00016   ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ 426f-512d ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -8ee8-a73 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 782…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ 267951f0- ┆ … ┆ nytimes-w ┆ 0.003989  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ 5577-5892 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -aaf5-332 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 82a…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ 09030f49- ┆ … ┆ nytimes-w ┆ 0.0002    ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ bcf1-52a3 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b090-215 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ bb9…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ d0988cbd- ┆ … ┆ nytimes-w ┆ 0.000178  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ 4fde-5d08 ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -b45d-00c ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 314…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
│ zhengqiao ┆ three     ┆ 2026-05-0 ┆ cf9b9186- ┆ … ┆ nytimes-w ┆ 0.000157  ┆ 1         ┆ pan26-ge │
│ zeng      ┆           ┆ 8-05-27-5 ┆ d7c3-5d7d ┆   ┆ riting-pr ┆           ┆           ┆ nerative │
│           ┆           ┆ 0         ┆ -8d76-c77 ┆   ┆ ompts-tra ┆           ┆           ┆ -ai-dete │
│           ┆           ┆           ┆ 025…      ┆   ┆ nsl…      ┆           ┆           ┆ ction-…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
def get_results_per_run(df: pl.DataFrame, drop_run_and_ds=False):
    group_cols = ['team', 'software', 'run_id', 'dataset']

    def evaluate_group(key, group_df):
        metrics = evaluate_all(
            group_df.select('label_truth'),
            group_df.select('label_pred'),
        )
        keys = pl.DataFrame([dict(zip(group_cols, key))])
        return pl.concat([keys, metrics], how='horizontal')

    df = pl.concat(
        evaluate_group(key, group_df)
        for key, group_df in df.partition_by(
            group_cols,
            as_dict=True,
            maintain_order=True,
        ).items()
    ).sort(by='mean', descending=True)
    if drop_run_and_ds:
        df = df.drop(['run_id', 'dataset'])
    return df

def get_best_by_team(result_per_run_df: pl.DataFrame, with_baselines=True):
    best_by_team = result_per_run_df.filter(pl.col('team') != 'baseline').unique(subset='team', keep='first', maintain_order=True)
    if not with_baselines:
        return best_by_team

    baseline_runs = result_per_run_df.filter(pl.col('team') == 'baseline')
    return pl.concat([best_by_team, baseline_runs]).sort('mean', descending=True)

In [8]:
results_per_run25 = get_results_per_run(pan25_df)
results_per_run26 = get_results_per_run(pan26_df)

In [9]:
display(Markdown('# PAN\'25 Dataset:'))
with pl.Config(float_precision=3, tbl_rows=-1):
    display(get_best_by_team(results_per_run25).drop(['dataset', 'run_id']))

# PAN'25 Dataset:

shape: (38, 10)
┌──────────────────────┬─────────────────────┬─────────┬───────┬───┬───────┬───────┬───────┬───────┐
│ team                 ┆ software            ┆ roc-auc ┆ brier ┆ … ┆ f05u  ┆ mean  ┆ fpr   ┆ fnr   │
│ ---                  ┆ ---                 ┆ ---     ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str                  ┆ str                 ┆ f64     ┆ f64   ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞══════════════════════╪═════════════════════╪═════════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ mdok                 ┆ mdok                ┆ 0.997   ┆ 0.988 ┆ … ┆ 0.994 ┆ 0.991 ┆ 0.006 ┆ 0.017 │
│ plagiarism-detector- ┆ alternating-conting ┆ 0.999   ┆ 0.986 ┆ … ┆ 0.992 ┆ 0.988 ┆ 0.001 ┆ 0.024 │
│ com-reg2             ┆ ency                ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ turingteam           ┆ marinated-edge      ┆ 0.995   ┆ 0.979 ┆ … ┆ 0.991 ┆ 0.986 ┆ 0.010 ┆ 0.025 │
│ dsgt-pan-26          ┆ relaxed-copy        ┆ 0.998   ┆ 0.977 ┆ … ┆ 0.990 ┆ 0.983 ┆ 0.005 ┆ 0.038 │
│ suspiciously-coheren ┆ lead-log            ┆ 0.998   ┆ 0.980 ┆ … ┆ 0.967 ┆ 0.979 ┆ 0.098 ┆ 0.001 │
│ t                    ┆                     ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ styloch2026          ┆ instant-tartar      ┆ 0.988   ┆ 0.967 ┆ … ┆ 0.989 ┆ 0.977 ┆ 0.003 ┆ 0.048 │
│ sst                  ┆ DeBERTa-V3-large-in ┆ 0.987   ┆ 0.969 ┆ … ┆ 0.987 ┆ 0.977 ┆ 0.010 ┆ 0.045 │
│                      ┆ dividual            ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ ak-ys                ┆ Qwen3-0.6B-fine-tun ┆ 0.991   ┆ 0.957 ┆ … ┆ 0.982 ┆ 0.968 ┆ 0.009 ┆ 0.069 │
│                      ┆ ed (dockerf…        ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ zhengqiaozeng        ┆ three               ┆ 0.978   ┆ 0.931 ┆ … ┆ 0.976 ┆ 0.952 ┆ 0.006 ┆ 0.099 │
│ ikr3                 ┆ lexical + semantic  ┆ 0.978   ┆ 0.939 ┆ … ┆ 0.974 ┆ 0.952 ┆ 0.008 ┆ 0.104 │
│                      ┆ avg                 ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ momifai              ┆ molten-deck         ┆ 0.981   ┆ 0.922 ┆ … ┆ 0.974 ┆ 0.948 ┆ 0.006 ┆ 0.109 │
│ codingmates          ┆ immediate-chimichan ┆ 0.973   ┆ 0.939 ┆ … ┆ 0.961 ┆ 0.947 ┆ 0.055 ┆ 0.089 │
│                      ┆ ga                  ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ writerslogic-inc     ┆ large-rank          ┆ 0.979   ┆ 0.935 ┆ … ┆ 0.959 ┆ 0.946 ┆ 0.061 ┆ 0.091 │
│ nai-long-zhan-dui    ┆ solid-capital       ┆ 0.973   ┆ 0.929 ┆ … ┆ 0.970 ┆ 0.945 ┆ 0.016 ┆ 0.111 │
│ radar                ┆ radar               ┆ 0.984   ┆ 0.917 ┆ … ┆ 0.971 ┆ 0.944 ┆ 0.005 ┆ 0.121 │
│ team-uit-huyygiaa    ┆ nice-frequency      ┆ 0.980   ┆ 0.919 ┆ … ┆ 0.969 ┆ 0.944 ┆ 0.015 ┆ 0.113 │
│ a-a-detection        ┆ navy-iceberg        ┆ 0.982   ┆ 0.899 ┆ … ┆ 0.952 ┆ 0.944 ┆ 0.111 ┆ 0.048 │
│ pinkey-bw            ┆ drab-cordon         ┆ 0.941   ┆ 0.928 ┆ … ┆ 0.971 ┆ 0.943 ┆ 0.025 ┆ 0.093 │
│ xlbn                 ┆ Grace               ┆ 0.969   ┆ 0.924 ┆ … ┆ 0.968 ┆ 0.941 ┆ 0.013 ┆ 0.119 │
│ baseline             ┆ baseline-tf-idf     ┆ 0.970   ┆ 0.918 ┆ … ┆ 0.960 ┆ 0.940 ┆ 0.055 ┆ 0.090 │
│ nexo                 ┆ skinny-pigeon       ┆ 0.971   ┆ 0.922 ┆ … ┆ 0.960 ┆ 0.940 ┆ 0.055 ┆ 0.106 │
│ chat-only            ┆ mashed-sweeper      ┆ 0.971   ┆ 0.923 ┆ … ┆ 0.968 ┆ 0.939 ┆ 0.006 ┆ 0.131 │
│ aitestchecking       ┆ nullary-velocity    ┆ 0.965   ┆ 0.922 ┆ … ┆ 0.967 ┆ 0.938 ┆ 0.011 ┆ 0.129 │
│ latentauthors        ┆ roaring-assurance   ┆ 0.960   ┆ 0.913 ┆ … ┆ 0.970 ┆ 0.937 ┆ 0.005 ┆ 0.127 │
│ ydong                ┆ arid-winch          ┆ 0.966   ┆ 0.935 ┆ … ┆ 0.935 ┆ 0.937 ┆ 0.155 ┆ 0.063 │
│ ce-ec                ┆ flavorful-raisin    ┆ 0.959   ┆ 0.914 ┆ … ┆ 0.960 ┆ 0.935 ┆ 0.043 ┆ 0.112 │
│ adnan-riad           ┆ Adv_E8_0.3          ┆ 0.966   ┆ 0.907 ┆ … ┆ 0.960 ┆ 0.933 ┆ 0.036 ┆ 0.122 │
│ spj                  ┆ wintry-burger       ┆ 0.952   ┆ 0.904 ┆ … ┆ 0.968 ┆ 0.931 ┆ 0.004 ┆ 0.137 │
│ egrantha-ai          ┆ finite-velour       ┆ 0.931   ┆ 0.908 ┆ … ┆ 0.968 ┆ 0.929 ┆ 0.010 ┆ 0.128 │
│ odean                ┆ narrow-lamb         ┆ 0.929   ┆ 0.908 ┆ … ┆ 0.966 ┆ 0.928 ┆ 0.017 ┆ 0.124 │
│ original             ┆ central-range       ┆ 0.933   ┆ 0.909 ┆ … ┆ 0.963 ┆ 0.925 ┆ 0.014 ┆ 0.141 │
│ manexagirrezabal     ┆ adventurous-drawbri ┆ 0.947   ┆ 0.906 ┆ … ┆ 0.954 ┆ 0.922 ┆ 0.038 ┆ 0.142 │
│                      ┆ dge                 ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ shushantatudublin    ┆ accepting-cut       ┆ 0.941   ┆ 0.893 ┆ … ┆ 0.957 ┆ 0.919 ┆ 0.024 ┆ 0.149 │
│ yjl                  ┆ antique-impulse     ┆ 0.945   ┆ 0.873 ┆ … ┆ 0.949 ┆ 0.905 ┆ 0.021 ┆ 0.184 │
│ uned-martinez        ┆ current-line        ┆ 0.933   ┆ 0.893 ┆ … ┆ 0.881 ┆ 0.891 ┆ 0.333 ┆ 0.077 │
│ baseline             ┆ baseline-ppmd       ┆ 0.723   ┆ 0.794 ┆ … ┆ 0.780 ┆ 0.765 ┆ 0.627 ┆ 0.124 │
│ baseline             ┆ baseline-binoculars ┆ 0.732   ┆ 0.654 ┆ … ┆ 0.649 ┆ 0.588 ┆ 0.011 ┆ 0.715 │
│                      ┆ -tiny-llama         ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ yihao                ┆ clear-buyer         ┆ 0.500   ┆ 0.750 ┆ … ┆ 0.000 ┆ 0.250 ┆ 1.000 ┆ 0.000 │
└──────────────────────┴─────────────────────┴─────────┴───────┴───┴───────┴───────┴───────┴───────┘

In [10]:
display(Markdown('# PAN\'26 Dataset:'))

best_by_team26 = get_best_by_team(results_per_run26)
leaderboard26 = best_by_team26.drop(['dataset', 'run_id'])

# xnoinspection PyTypeChecker
zero_knowledge_pan26 = pl.DataFrame({
    "team": "baseline",
    "software": "baseline-zero-knowledge",
    "roc-auc": 0.5,
    "brier": 0.749,
    "c@1": 0.749,
    "f1": 0.856,
    "f05u": 0.788,
    "mean": 0.728,
    "fpr": 1.0,
    "fnr": 0.0,
})

leaderboard26 = (
    pl
    .concat([leaderboard26, zero_knowledge_pan26])
    .sort('mean', descending=True)
    .with_columns([
        pl.col("team").replace("mdok", "baseline"),
        pl.col("software").replace("mdok", "baseline-mdok"),
    ])
)

leaderboard26.to_pandas().to_html(BASE_EVAL_PATH / 'pan26-leaderboard.html', index=True, float_format=lambda x: f"{x:.3f}")

with pl.Config(float_precision=3, tbl_rows=-1):
    display(leaderboard26)

# PAN'26 Dataset:

shape: (39, 10)
┌──────────────────────┬─────────────────────┬─────────┬───────┬───┬───────┬───────┬───────┬───────┐
│ team                 ┆ software            ┆ roc-auc ┆ brier ┆ … ┆ f05u  ┆ mean  ┆ fpr   ┆ fnr   │
│ ---                  ┆ ---                 ┆ ---     ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str                  ┆ str                 ┆ f64     ┆ f64   ┆   ┆ f64   ┆ f64   ┆ f64   ┆ f64   │
╞══════════════════════╪═════════════════════╪═════════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ suspiciously-coheren ┆ lead-log            ┆ 0.989   ┆ 0.965 ┆ … ┆ 0.980 ┆ 0.975 ┆ 0.053 ┆ 0.029 │
│ t                    ┆                     ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ sst                  ┆ ModernBERT-large-BN ┆ 0.993   ┆ 0.970 ┆ … ┆ 0.969 ┆ 0.974 ┆ 0.108 ┆ 0.014 │
│                      ┆ N                   ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ baseline             ┆ baseline-mdok       ┆ 0.995   ┆ 0.951 ┆ … ┆ 0.984 ┆ 0.968 ┆ 0.002 ┆ 0.072 │
│ plagiarism-detector- ┆ alternating-conting ┆ 0.996   ┆ 0.941 ┆ … ┆ 0.957 ┆ 0.946 ┆ 0.000 ┆ 0.072 │
│ com-reg2             ┆ ency                ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ dsgt-pan-26          ┆ relaxed-copy        ┆ 0.981   ┆ 0.885 ┆ … ┆ 0.961 ┆ 0.921 ┆ 0.000 ┆ 0.170 │
│ ydong                ┆ arid-winch          ┆ 0.930   ┆ 0.915 ┆ … ┆ 0.896 ┆ 0.911 ┆ 0.420 ┆ 0.014 │
│ turingteam           ┆ marinated-edge      ┆ 0.957   ┆ 0.882 ┆ … ┆ 0.925 ┆ 0.892 ┆ 0.053 ┆ 0.179 │
│ writerslogic-inc     ┆ large-rank          ┆ 0.891   ┆ 0.891 ┆ … ┆ 0.899 ┆ 0.887 ┆ 0.312 ┆ 0.092 │
│ a-a-detection        ┆ navy-iceberg        ┆ 0.852   ┆ 0.848 ┆ … ┆ 0.880 ┆ 0.858 ┆ 0.375 ┆ 0.106 │
│ baseline             ┆ baseline-ppmd       ┆ 0.783   ┆ 0.810 ┆ … ┆ 0.828 ┆ 0.814 ┆ 0.728 ┆ 0.066 │
│ ak-ys                ┆ Qwen3-14B-fine-tune ┆ 0.911   ┆ 0.754 ┆ … ┆ 0.891 ┆ 0.811 ┆ 0.016 ┆ 0.365 │
│                      ┆ d                   ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ ikr3                 ┆ lexical +           ┆ 0.814   ┆ 0.779 ┆ … ┆ 0.788 ┆ 0.797 ┆ 1.000 ┆ 0.000 │
│                      ┆ linguistic LR       ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ ce-ec                ┆ atomic-fruit        ┆ 0.624   ┆ 0.771 ┆ … ┆ 0.788 ┆ 0.757 ┆ 1.000 ┆ 0.001 │
│ egrantha-ai          ┆ faded-noir          ┆ 0.500   ┆ 0.749 ┆ … ┆ 0.788 ┆ 0.728 ┆ 1.000 ┆ 0.000 │
│ baseline             ┆ baseline-zero-knowl ┆ 0.500   ┆ 0.749 ┆ … ┆ 0.788 ┆ 0.728 ┆ 1.000 ┆ 0.000 │
│                      ┆ edge                ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ odean                ┆ narrow-lamb         ┆ 0.732   ┆ 0.624 ┆ … ┆ 0.823 ┆ 0.695 ┆ 0.051 ┆ 0.485 │
│ codingmates          ┆ silent-screen       ┆ 0.756   ┆ 0.682 ┆ … ┆ 0.768 ┆ 0.687 ┆ 0.178 ┆ 0.448 │
│ adnan-riad           ┆ ADV_05_new          ┆ 0.856   ┆ 0.658 ┆ … ┆ 0.764 ┆ 0.682 ┆ 0.036 ┆ 0.588 │
│ styloch2026          ┆ instant-tartar      ┆ 0.931   ┆ 0.572 ┆ … ┆ 0.744 ┆ 0.662 ┆ 0.002 ┆ 0.632 │
│ momifai              ┆ molten-deck         ┆ 0.867   ┆ 0.536 ┆ … ┆ 0.744 ┆ 0.645 ┆ 0.024 ┆ 0.621 │
│ team-uit-huyygiaa    ┆ nice-frequency      ┆ 0.779   ┆ 0.555 ┆ … ┆ 0.756 ┆ 0.638 ┆ 0.018 ┆ 0.609 │
│ shushantatudublin    ┆ similar-factor      ┆ 0.856   ┆ 0.602 ┆ … ┆ 0.708 ┆ 0.632 ┆ 0.014 ┆ 0.668 │
│ radar                ┆ radar               ┆ 0.790   ┆ 0.541 ┆ … ┆ 0.741 ┆ 0.632 ┆ 0.055 ┆ 0.609 │
│ yjl                  ┆ antique-impulse     ┆ 0.649   ┆ 0.553 ┆ … ┆ 0.751 ┆ 0.615 ┆ 0.075 ┆ 0.585 │
│ uned-martinez        ┆ current-line        ┆ 0.603   ┆ 0.643 ┆ … ┆ 0.700 ┆ 0.604 ┆ 0.274 ┆ 0.563 │
│ manexagirrezabal     ┆ adventurous-drawbri ┆ 0.711   ┆ 0.618 ┆ … ┆ 0.692 ┆ 0.601 ┆ 0.061 ┆ 0.664 │
│                      ┆ dge                 ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ xlbn                 ┆ Grace               ┆ 0.792   ┆ 0.559 ┆ … ┆ 0.674 ┆ 0.593 ┆ 0.028 ┆ 0.671 │
│ chat-only            ┆ mashed-sweeper      ┆ 0.801   ┆ 0.565 ┆ … ┆ 0.669 ┆ 0.591 ┆ 0.022 ┆ 0.704 │
│ original             ┆ central-range       ┆ 0.681   ┆ 0.559 ┆ … ┆ 0.708 ┆ 0.590 ┆ 0.016 ┆ 0.648 │
│ baseline             ┆ baseline-tf-idf     ┆ 0.711   ┆ 0.686 ┆ … ┆ 0.637 ┆ 0.586 ┆ 0.069 ┆ 0.651 │
│ nexo                 ┆ skinny-pigeon       ┆ 0.651   ┆ 0.541 ┆ … ┆ 0.703 ┆ 0.580 ┆ 0.075 ┆ 0.638 │
│ pinkey-bw            ┆ drab-cordon         ┆ 0.660   ┆ 0.504 ┆ … ┆ 0.716 ┆ 0.579 ┆ 0.026 ┆ 0.654 │
│ aitestchecking       ┆ nullary-velocity    ┆ 0.802   ┆ 0.562 ┆ … ┆ 0.645 ┆ 0.577 ┆ 0.006 ┆ 0.731 │
│ nai-long-zhan-dui    ┆ solid-capital       ┆ 0.690   ┆ 0.549 ┆ … ┆ 0.670 ┆ 0.570 ┆ 0.055 ┆ 0.668 │
│ latentauthors        ┆ roaring-assurance   ┆ 0.750   ┆ 0.486 ┆ … ┆ 0.678 ┆ 0.569 ┆ 0.008 ┆ 0.701 │
│ zhengqiaozeng        ┆ three               ┆ 0.753   ┆ 0.464 ┆ … ┆ 0.661 ┆ 0.556 ┆ 0.002 ┆ 0.719 │
│ spj                  ┆ wintry-burger       ┆ 0.772   ┆ 0.437 ┆ … ┆ 0.620 ┆ 0.532 ┆ 0.000 ┆ 0.754 │
│ baseline             ┆ baseline-binoculars ┆ 0.681   ┆ 0.596 ┆ … ┆ 0.422 ┆ 0.455 ┆ 0.012 ┆ 0.863 │
│                      ┆ -tiny-llama         ┆         ┆       ┆   ┆       ┆       ┆       ┆       │
│ yihao                ┆ clear-buyer         ┆ 0.500   ┆ 0.750 ┆ … ┆ 0.000 ┆ 0.250 ┆ 1.000 ┆ 0.000 │
└──────────────────────┴─────────────────────┴─────────┴───────┴───┴───────┴───────┴───────┴───────┘

In [11]:
pan26_df_filtered_best = pan26_df.join(
    best_by_team26.select('run_id').unique(),
    on='run_id',
    how='semi'
)
pan26_df.select('source').unique()

shape: (8, 1)
┌─────────────────────────────────┐
│ source                          │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ nytimes-writing-prompts-revers… │
│ nytimes-writing-prompts         │
│ nytimes-writing-prompts-tibet-… │
│ brown-cont                      │
│ nytimes-writing-prompts-transl… │
│ brown                           │
│ nytimes-writing-prompts-tibet-… │
│ nytimes-writing-prompts-tibet-… │
└─────────────────────────────────┘

In [12]:
get_results_per_run(pan26_df_filtered_best.filter(
    pl.col('source').str.starts_with('brown')
), drop_run_and_ds=True)

shape: (38, 10)
┌────────────────┬───────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────┐
│ team           ┆ software      ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr  │
│ ---            ┆ ---           ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str            ┆ str           ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞════════════════╪═══════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ suspiciously-c ┆ lead-log      ┆ 0.897922 ┆ 0.90321  ┆ … ┆ 0.743534 ┆ 0.827456 ┆ 0.071429 ┆ 0.31 │
│ oherent        ┆               ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ turingteam     ┆ marinated-edg ┆ 0.881867 ┆ 0.890409 ┆ … ┆ 0.716463 ┆ 0.790839 ┆ 0.042208 ┆ 0.45 │
│                ┆ e             ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ sst            ┆ ModernBERT-la ┆ 0.872825 ┆ 0.871369 ┆ … ┆ 0.653226 ┆ 0.78702  ┆ 0.159091 ┆ 0.19 │
│                ┆ rge-BNN       ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ odean          ┆ narrow-lamb   ┆ 0.767532 ┆ 0.852941 ┆ … ┆ 0.714286 ┆ 0.770873 ┆ 0.064935 ┆ 0.4  │
│ yjl            ┆ antique-impul ┆ 0.868961 ┆ 0.844802 ┆ … ┆ 0.683333 ┆ 0.755419 ┆ 0.029221 ┆ 0.59 │
│                ┆ se            ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ …              ┆ …             ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …    │
│ ce-ec          ┆ atomic-fruit  ┆ 0.487711 ┆ 0.723561 ┆ … ┆ 0.288684 ┆ 0.427751 ┆ 1.0      ┆ 0.0  │
│ ikr3           ┆ lexical +     ┆ 0.846851 ┆ 0.339221 ┆ … ┆ 0.288684 ┆ 0.422711 ┆ 1.0      ┆ 0.0  │
│                ┆ linguistic LR ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ uned-martinez  ┆ current-line  ┆ 0.492273 ┆ 0.767011 ┆ … ┆ 0.053763 ┆ 0.411582 ┆ 0.068182 ┆ 0.98 │
│ egrantha-ai    ┆ faded-noir    ┆ 0.5      ┆ 0.245098 ┆ … ┆ 0.288684 ┆ 0.334516 ┆ 1.0      ┆ 0.0  │
│ yihao          ┆ clear-buyer   ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0  │
└────────────────┴───────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────┘

In [13]:
get_results_per_run(pan26_df_filtered_best.filter(
    (pl.col('source') == 'nytimes-writing-prompts-tibet-translated-en') |
    ((pl.col('source') == 'nytimes-writing-prompts') & (pl.col('label_truth') == 0))
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ mdok         ┆ mdok        ┆ 0.999949 ┆ 0.994874 ┆ … ┆ 0.994975 ┆ 0.99595  ┆ 0.005025 ┆ 0.005025 │
│ dsgt-pan-26  ┆ relaxed-cop ┆ 1.0      ┆ 0.993111 ┆ … ┆ 0.996948 ┆ 0.994985 ┆ 0.0      ┆ 0.015075 │
│              ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ suspiciously ┆ lead-log    ┆ 0.999747 ┆ 0.985155 ┆ … ┆ 0.979228 ┆ 0.986826 ┆ 0.025126 ┆ 0.005025 │
│ -coherent    ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ sst          ┆ ModernBERT- ┆ 0.999975 ┆ 0.985144 ┆ … ┆ 0.976447 ┆ 0.986328 ┆ 0.030151 ┆ 0.0      │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 1.0      ┆ 0.976415 ┆ … ┆ 0.965714 ┆ 0.969591 ┆ 0.0      ┆ 0.015075 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ nexo         ┆ skinny-pige ┆ 0.355799 ┆ 0.493629 ┆ … ┆ 0.0      ┆ 0.259141 ┆ 0.135678 ┆ 0.994975 │
│              ┆ on          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ uned-martine ┆ current-lin ┆ 0.15309  ┆ 0.524158 ┆ … ┆ 0.169377 ┆ 0.254944 ┆ 0.592965 ┆ 0.849246 │
│ z            ┆ e           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
│ nai-long-zha ┆ solid-capit ┆ 0.203959 ┆ 0.493837 ┆ … ┆ 0.01845  ┆ 0.236917 ┆ 0.100503 ┆ 0.984925 │
│ n-dui        ┆ al          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ yjl          ┆ antique-imp ┆ 0.240916 ┆ 0.449187 ┆ … ┆ 0.015674 ┆ 0.228832 ┆ 0.145729 ┆ 0.994975 │
│              ┆ ulse        ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [14]:
get_results_per_run(pan26_df_filtered_best.filter(
    (pl.col('source') == 'nytimes-writing-prompts-tibet-translated-en-zh-fa-en') |
    ((pl.col('source') == 'nytimes-writing-prompts') & (pl.col('label_truth') == 0))
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ mdok         ┆ mdok        ┆ 0.999697 ┆ 0.991744 ┆ … ┆ 0.992908 ┆ 0.99284  ┆ 0.005025 ┆ 0.015075 │
│ sst          ┆ ModernBERT- ┆ 0.999848 ┆ 0.984997 ┆ … ┆ 0.976447 ┆ 0.986273 ┆ 0.030151 ┆ 0.0      │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ suspiciously ┆ lead-log    ┆ 0.999545 ┆ 0.981349 ┆ … ┆ 0.979228 ┆ 0.986024 ┆ 0.025126 ┆ 0.005025 │
│ -coherent    ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ ak-ys        ┆ Qwen3-14B-f ┆ 0.996048 ┆ 0.973379 ┆ … ┆ 0.973223 ┆ 0.974352 ┆ 0.020101 ┆ 0.050251 │
│              ┆ ine-tuned   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 0.999848 ┆ 0.975329 ┆ … ┆ 0.970819 ┆ 0.97108  ┆ 0.0      ┆ 0.035176 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ zhengqiaozen ┆ three       ┆ 0.579051 ┆ 0.500328 ┆ … ┆ 0.0      ┆ 0.315876 ┆ 0.0      ┆ 1.0      │
│ g            ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ nexo         ┆ skinny-pige ┆ 0.508346 ┆ 0.510816 ┆ … ┆ 0.053004 ┆ 0.311217 ┆ 0.135678 ┆ 0.969849 │
│              ┆ on          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ nai-long-zha ┆ solid-capit ┆ 0.309285 ┆ 0.524749 ┆ … ┆ 0.053763 ┆ 0.27613  ┆ 0.100503 ┆ 0.969849 │
│ n-dui        ┆ al          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
│ yjl          ┆ antique-imp ┆ 0.272455 ┆ 0.45007  ┆ … ┆ 0.03096  ┆ 0.240607 ┆ 0.145729 ┆ 0.98995  │
│              ┆ ulse        ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [15]:
get_results_per_run(pan26_df_filtered_best.filter(
    (pl.col('source') == 'nytimes-writing-prompts-tibet-translated-mr-kk-ja-lo-iw-am-en') |
    ((pl.col('source') == 'nytimes-writing-prompts') & (pl.col('label_truth') == 0))
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ suspiciously ┆ lead-log    ┆ 0.999722 ┆ 0.98156  ┆ … ┆ 0.980296 ┆ 0.987322 ┆ 0.025126 ┆ 0.0      │
│ -coherent    ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ sst          ┆ ModernBERT- ┆ 0.999924 ┆ 0.985017 ┆ … ┆ 0.976447 ┆ 0.986292 ┆ 0.030151 ┆ 0.0      │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 0.999369 ┆ 0.975389 ┆ … ┆ 0.983176 ┆ 0.978336 ┆ 0.005025 ┆ 0.060302 │
│ ak-ys        ┆ Qwen3-14B-f ┆ 0.996439 ┆ 0.976785 ┆ … ┆ 0.975485 ┆ 0.97762  ┆ 0.020101 ┆ 0.040201 │
│              ┆ ine-tuned   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 0.999369 ┆ 0.956427 ┆ … ┆ 0.946276 ┆ 0.948642 ┆ 0.0      ┆ 0.050251 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ latentauthor ┆ roaring-ass ┆ 0.606121 ┆ 0.500353 ┆ … ┆ 0.0      ┆ 0.319787 ┆ 0.015075 ┆ 1.0      │
│ s            ┆ urance      ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ original     ┆ central-ran ┆ 0.496957 ┆ 0.548604 ┆ … ┆ 0.042918 ┆ 0.319764 ┆ 0.040201 ┆ 0.974874 │
│              ┆ ge          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ uned-martine ┆ current-lin ┆ 0.162913 ┆ 0.539265 ┆ … ┆ 0.169377 ┆ 0.259662 ┆ 0.592965 ┆ 0.859296 │
│ z            ┆ e           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
│ yjl          ┆ antique-imp ┆ 0.2945   ┆ 0.45121  ┆ … ┆ 0.03096  ┆ 0.245244 ┆ 0.145729 ┆ 0.98995  │
│              ┆ ulse        ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [16]:
get_results_per_run(pan26_df_filtered_best.filter(
    (pl.col('source') == 'nytimes-writing-prompts-translated-en-obfs') |
    ((pl.col('source') == 'nytimes-writing-prompts') & (pl.col('label_truth') == 0))
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ dsgt-pan-26  ┆ relaxed-cop ┆ 1.0      ┆ 0.99997  ┆ … ┆ 1.0      ┆ 0.999994 ┆ 0.0      ┆ 0.0      │
│              ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 0.999899 ┆ 0.996646 ┆ … ┆ 0.994975 ┆ 0.996294 ┆ 0.005025 ┆ 0.005025 │
│ sst          ┆ ModernBERT- ┆ 0.999874 ┆ 0.98496  ┆ … ┆ 0.976447 ┆ 0.986271 ┆ 0.030151 ┆ 0.0      │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ suspiciously ┆ lead-log    ┆ 0.999293 ┆ 0.974368 ┆ … ┆ 0.980296 ┆ 0.985797 ┆ 0.025126 ┆ 0.0      │
│ -coherent    ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 1.0      ┆ 0.972112 ┆ … ┆ 0.964409 ┆ 0.967807 ┆ 0.0      ┆ 0.015075 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ yjl          ┆ antique-imp ┆ 0.256294 ┆ 0.448123 ┆ … ┆ 0.0      ┆ 0.226311 ┆ 0.145729 ┆ 1.0      │
│              ┆ ulse        ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ team-uit-huy ┆ nice-freque ┆ 0.112131 ┆ 0.494665 ┆ … ┆ 0.0      ┆ 0.220354 ┆ 0.01005  ┆ 1.0      │
│ ygiaa        ┆ ncy         ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ nai-long-zha ┆ solid-capit ┆ 0.160274 ┆ 0.48294  ┆ … ┆ 0.0      ┆ 0.219496 ┆ 0.100503 ┆ 1.0      │
│ n-dui        ┆ al          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ nexo         ┆ skinny-pige ┆ 0.041767 ┆ 0.481702 ┆ … ┆ 0.0      ┆ 0.193732 ┆ 0.135678 ┆ 1.0      │
│              ┆ on          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ uned-martine ┆ current-lin ┆ 0.006818 ┆ 0.376446 ┆ … ┆ 0.0      ┆ 0.118481 ┆ 0.592965 ┆ 1.0      │
│ z            ┆ e           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [17]:
get_results_per_run(pan26_df_filtered_best.filter(
    (pl.col('source') == 'nytimes-writing-prompts-reverse-swahili-translated') |
    ((pl.col('source') == 'nytimes-writing-prompts') & (pl.col('label_truth') == 0))
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ dsgt-pan-26  ┆ relaxed-cop ┆ 0.999641 ┆ 0.980479 ┆ … ┆ 0.925926 ┆ 0.94412  ┆ 0.0      ┆ 0.285714 │
│              ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 0.991385 ┆ 0.975993 ┆ … ┆ 0.862069 ┆ 0.921195 ┆ 0.005025 ┆ 0.285714 │
│ sst          ┆ ModernBERT- ┆ 0.990668 ┆ 0.969334 ┆ … ┆ 0.722222 ┆ 0.887448 ┆ 0.030151 ┆ 0.071429 │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 0.999282 ┆ 0.98313  ┆ … ┆ 0.666667 ┆ 0.814684 ┆ 0.0      ┆ 0.285714 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ turingteam   ┆ marinated-e ┆ 0.856425 ┆ 0.918626 ┆ … ┆ 0.4375   ┆ 0.726115 ┆ 0.070352 ┆ 0.357143 │
│              ┆ dge         ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ codingmates  ┆ silent-scre ┆ 0.142498 ┆ 0.625029 ┆ … ┆ 0.016667 ┆ 0.28159  ┆ 0.39196  ┆ 0.928571 │
│              ┆ en          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
│ uned-martine ┆ current-lin ┆ 0.13855  ┆ 0.606582 ┆ … ┆ 0.021692 ┆ 0.241828 ┆ 0.592965 ┆ 0.857143 │
│ z            ┆ e           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ ikr3         ┆ lexical +   ┆ 0.750179 ┆ 0.185873 ┆ … ┆ 0.080831 ┆ 0.241192 ┆ 1.0      ┆ 0.0      │
│              ┆ linguistic  ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│              ┆ LR          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ egrantha-ai  ┆ faded-noir  ┆ 0.5      ┆ 0.065728 ┆ … ┆ 0.080831 ┆ 0.167127 ┆ 1.0      ┆ 0.0      │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [18]:
pan26_df.select('model').unique()

shape: (7, 1)
┌─────────────────────────────────┐
│ model                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ llama-3.3-70b-instruct-8bit-rt… │
│ llama-3.3-70b-instruct-8bit-wa… │
│ gpt-5.4                         │
│ gpt-4o                          │
│ human                           │
│ gpt-5.5                         │
│ nytimes-writing-prompts-transl… │
└─────────────────────────────────┘

In [19]:
get_results_per_run(pan26_df_filtered_best.filter(
    ((pl.col('model') == 'gpt-5.5') | (pl.col('model') == 'human')) &
    pl.col('source').str.starts_with('brown')
), drop_run_and_ds=True)

shape: (38, 10)
┌────────────────┬───────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────┐
│ team           ┆ software      ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr  │
│ ---            ┆ ---           ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---  │
│ str            ┆ str           ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64  │
╞════════════════╪═══════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════╡
│ suspiciously-c ┆ lead-log      ┆ 0.897922 ┆ 0.90321  ┆ … ┆ 0.743534 ┆ 0.827456 ┆ 0.071429 ┆ 0.31 │
│ oherent        ┆               ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ turingteam     ┆ marinated-edg ┆ 0.881867 ┆ 0.890409 ┆ … ┆ 0.716463 ┆ 0.790839 ┆ 0.042208 ┆ 0.45 │
│                ┆ e             ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ sst            ┆ ModernBERT-la ┆ 0.872825 ┆ 0.871369 ┆ … ┆ 0.653226 ┆ 0.78702  ┆ 0.159091 ┆ 0.19 │
│                ┆ rge-BNN       ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ odean          ┆ narrow-lamb   ┆ 0.767532 ┆ 0.852941 ┆ … ┆ 0.714286 ┆ 0.770873 ┆ 0.064935 ┆ 0.4  │
│ yjl            ┆ antique-impul ┆ 0.868961 ┆ 0.844802 ┆ … ┆ 0.683333 ┆ 0.755419 ┆ 0.029221 ┆ 0.59 │
│                ┆ se            ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ …              ┆ …             ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …    │
│ ce-ec          ┆ atomic-fruit  ┆ 0.487711 ┆ 0.723561 ┆ … ┆ 0.288684 ┆ 0.427751 ┆ 1.0      ┆ 0.0  │
│ ikr3           ┆ lexical +     ┆ 0.846851 ┆ 0.339221 ┆ … ┆ 0.288684 ┆ 0.422711 ┆ 1.0      ┆ 0.0  │
│                ┆ linguistic LR ┆          ┆          ┆   ┆          ┆          ┆          ┆      │
│ uned-martinez  ┆ current-line  ┆ 0.492273 ┆ 0.767011 ┆ … ┆ 0.053763 ┆ 0.411582 ┆ 0.068182 ┆ 0.98 │
│ egrantha-ai    ┆ faded-noir    ┆ 0.5      ┆ 0.245098 ┆ … ┆ 0.288684 ┆ 0.334516 ┆ 1.0      ┆ 0.0  │
│ yihao          ┆ clear-buyer   ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0  │
└────────────────┴───────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────┘

In [20]:
get_results_per_run(pan26_df_filtered_best.filter(
    ((pl.col('model') == 'gpt-5.5') | (pl.col('model') == 'human')) &
    pl.col('source').str.starts_with('nytimes')
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ dsgt-pan-26  ┆ relaxed-cop ┆ 0.999641 ┆ 0.980479 ┆ … ┆ 0.925926 ┆ 0.94412  ┆ 0.0      ┆ 0.285714 │
│              ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 0.991385 ┆ 0.975993 ┆ … ┆ 0.862069 ┆ 0.921195 ┆ 0.005025 ┆ 0.285714 │
│ sst          ┆ ModernBERT- ┆ 0.990668 ┆ 0.969334 ┆ … ┆ 0.722222 ┆ 0.887448 ┆ 0.030151 ┆ 0.071429 │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 0.999282 ┆ 0.98313  ┆ … ┆ 0.666667 ┆ 0.814684 ┆ 0.0      ┆ 0.285714 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ turingteam   ┆ marinated-e ┆ 0.856425 ┆ 0.918626 ┆ … ┆ 0.4375   ┆ 0.726115 ┆ 0.070352 ┆ 0.357143 │
│              ┆ dge         ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ codingmates  ┆ silent-scre ┆ 0.142498 ┆ 0.625029 ┆ … ┆ 0.016667 ┆ 0.28159  ┆ 0.39196  ┆ 0.928571 │
│              ┆ en          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
│ uned-martine ┆ current-lin ┆ 0.13855  ┆ 0.606582 ┆ … ┆ 0.021692 ┆ 0.241828 ┆ 0.592965 ┆ 0.857143 │
│ z            ┆ e           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ ikr3         ┆ lexical +   ┆ 0.750179 ┆ 0.185873 ┆ … ┆ 0.080831 ┆ 0.241192 ┆ 1.0      ┆ 0.0      │
│              ┆ linguistic  ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│              ┆ LR          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ egrantha-ai  ┆ faded-noir  ┆ 0.5      ┆ 0.065728 ┆ … ┆ 0.080831 ┆ 0.167127 ┆ 1.0      ┆ 0.0      │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [21]:
get_results_per_run(pan26_df_filtered_best.filter(
    ((pl.col('model') == 'gpt-5.4') | (pl.col('model') == 'human')) &
    pl.col('source').str.starts_with('nytimes')
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ sst          ┆ ModernBERT- ┆ 0.999937 ┆ 0.993899 ┆ … ┆ 0.994006 ┆ 0.995611 ┆ 0.030151 ┆ 0.0      │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ suspiciously ┆ lead-log    ┆ 0.999716 ┆ 0.98314  ┆ … ┆ 0.994489 ┆ 0.993184 ┆ 0.025126 ┆ 0.002513 │
│ -coherent    ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 0.999754 ┆ 0.986694 ┆ … ┆ 0.994898 ┆ 0.990696 ┆ 0.005025 ┆ 0.020101 │
│ plagiarism-d ┆ alternating ┆ 0.999804 ┆ 0.963692 ┆ … ┆ 0.972067 ┆ 0.968072 ┆ 0.0      ┆ 0.025126 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ ydong        ┆ arid-winch  ┆ 0.932792 ┆ 0.918541 ┆ … ┆ 0.901826 ┆ 0.915099 ┆ 0.547739 ┆ 0.007538 │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ nai-long-zha ┆ solid-capit ┆ 0.403001 ┆ 0.368068 ┆ … ┆ 0.334746 ┆ 0.310052 ┆ 0.100503 ┆ 0.86809  │
│ n-dui        ┆ al          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ aitestchecki ┆ nullary-vel ┆ 0.777158 ┆ 0.389424 ┆ … ┆ 0.112613 ┆ 0.309024 ┆ 0.015075 ┆ 0.974874 │
│ ng           ┆ ocity       ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ zhengqiaozen ┆ three       ┆ 0.638488 ┆ 0.234117 ┆ … ┆ 0.163755 ┆ 0.26783  ┆ 0.0      ┆ 0.962312 │
│ g            ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ spj          ┆ wintry-burg ┆ 0.795636 ┆ 0.212123 ┆ … ┆ 0.065476 ┆ 0.26231  ┆ 0.0      ┆ 0.986181 │
│              ┆ er          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [22]:
get_results_per_run(pan26_df_filtered_best.filter(
    ((pl.col('model') == 'gpt-4o') | (pl.col('model') == 'human')) &
    pl.col('source').str.starts_with('nytimes')
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ dsgt-pan-26  ┆ relaxed-cop ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 0.0      ┆ 0.0      │
│              ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ spj          ┆ wintry-burg ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 0.0      ┆ 0.0      │
│              ┆ er          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ zhengqiaozen ┆ three       ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 0.0      ┆ 0.0      │
│ g            ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 1.0      ┆ 0.999453 ┆ … ┆ 1.0      ┆ 0.999891 ┆ 0.0      ┆ 0.0      │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 1.0      ┆ 0.997637 ┆ … ┆ 0.995996 ┆ 0.997723 ┆ 0.005025 ┆ 0.0      │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ baseline     ┆ baseline-pp ┆ 0.81806  ┆ 0.775101 ┆ … ┆ 0.626186 ┆ 0.714493 ┆ 0.809045 ┆ 0.005025 │
│              ┆ md          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ ce-ec        ┆ atomic-frui ┆ 0.821949 ┆ 0.748857 ┆ … ┆ 0.555556 ┆ 0.658606 ┆ 1.0      ┆ 0.0      │
│              ┆ t           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ ikr3         ┆ lexical +   ┆ 1.0      ┆ 0.564416 ┆ … ┆ 0.555556 ┆ 0.657328 ┆ 1.0      ┆ 0.0      │
│              ┆ linguistic  ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│              ┆ LR          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ egrantha-ai  ┆ faded-noir  ┆ 0.5      ┆ 0.5      ┆ … ┆ 0.555556 ┆ 0.544444 ┆ 1.0      ┆ 0.0      │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [23]:
get_results_per_run(pan26_df_filtered_best.filter(
    ((pl.col('model') == 'llama-3.3-70b-instruct-8bit-rtop1') | (pl.col('model') == 'human')) &
    pl.col('source').str.starts_with('nytimes')
), drop_run_and_ds=True)

shape: (38, 10)
┌────────────────┬────────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬─────┐
│ team           ┆ software       ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr │
│ ---            ┆ ---            ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ --- │
│ str            ┆ str            ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64 │
╞════════════════╪════════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪═════╡
│ spj            ┆ wintry-burger  ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 0.0      ┆ 0.0 │
│ dsgt-pan-26    ┆ relaxed-copy   ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 0.0      ┆ 0.0 │
│ zhengqiaozeng  ┆ three          ┆ 1.0      ┆ 1.0      ┆ … ┆ 1.0      ┆ 1.0      ┆ 0.0      ┆ 0.0 │
│ plagiarism-det ┆ alternating-co ┆ 1.0      ┆ 0.998922 ┆ … ┆ 1.0      ┆ 0.999784 ┆ 0.0      ┆ 0.0 │
│ ector-com-reg2 ┆ ntingency      ┆          ┆          ┆   ┆          ┆          ┆          ┆     │
│ baseline       ┆ baseline-binoc ┆ 1.0      ┆ 0.988863 ┆ … ┆ 1.0      ┆ 0.997773 ┆ 0.0      ┆ 0.0 │
│                ┆ ulars-tiny-lla ┆          ┆          ┆   ┆          ┆          ┆          ┆     │
│                ┆ ma             ┆          ┆          ┆   ┆          ┆          ┆          ┆     │
│ …              ┆ …              ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …   │
│ baseline       ┆ baseline-ppmd  ┆ 0.9933   ┆ 0.69547  ┆ … ┆ 0.024793 ┆ 0.394978 ┆ 0.809045 ┆ 0.0 │
│ ce-ec          ┆ atomic-fruit   ┆ 0.834171 ┆ 0.70335  ┆ … ┆ 0.018496 ┆ 0.320027 ┆ 1.0      ┆ 0.0 │
│ yihao          ┆ clear-buyer    ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0 │
│ ikr3           ┆ lexical +      ┆ 1.0      ┆ 0.141771 ┆ … ┆ 0.018496 ┆ 0.240877 ┆ 1.0      ┆ 0.0 │
│                ┆ linguistic LR  ┆          ┆          ┆   ┆          ┆          ┆          ┆     │
│ egrantha-ai    ┆ faded-noir     ┆ 0.5      ┆ 0.014851 ┆ … ┆ 0.018496 ┆ 0.115493 ┆ 1.0      ┆ 0.0 │
└────────────────┴────────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴─────┘

In [24]:
get_results_per_run(pan26_df_filtered_best.filter(
    ((pl.col('model') == 'llama-3.3-70b-instruct-8bit-watermark-gamma05-bias5-temp1') | (pl.col('model') == 'human')) &
    pl.col('source').str.starts_with('nytimes')
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ dsgt-pan-26  ┆ relaxed-cop ┆ 1.0      ┆ 0.998187 ┆ … ┆ 0.998991 ┆ 0.998429 ┆ 0.0      ┆ 0.005025 │
│              ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 1.0      ┆ 0.997637 ┆ … ┆ 0.995996 ┆ 0.997723 ┆ 0.005025 ┆ 0.0      │
│ team-uit-huy ┆ nice-freque ┆ 0.998056 ┆ 0.989213 ┆ … ┆ 0.98995  ┆ 0.991424 ┆ 0.01005  ┆ 0.01005  │
│ ygiaa        ┆ ncy         ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ suspiciously ┆ lead-log    ┆ 0.999874 ┆ 0.990422 ┆ … ┆ 0.980296 ┆ 0.989124 ┆ 0.025126 ┆ 0.0      │
│ -coherent    ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ zhengqiaozen ┆ three       ┆ 0.999924 ┆ 0.984262 ┆ … ┆ 0.992761 ┆ 0.988291 ┆ 0.0      ┆ 0.035176 │
│ g            ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ ce-ec        ┆ atomic-frui ┆ 0.643658 ┆ 0.74675  ┆ … ┆ 0.554001 ┆ 0.621265 ┆ 1.0      ┆ 0.005025 │
│              ┆ t           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ codingmates  ┆ silent-scre ┆ 0.557145 ┆ 0.659647 ┆ … ┆ 0.573678 ┆ 0.59086  ┆ 0.39196  ┆ 0.356784 │
│              ┆ en          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ baseline     ┆ baseline-pp ┆ 0.613368 ┆ 0.735293 ┆ … ┆ 0.489591 ┆ 0.562839 ┆ 0.809045 ┆ 0.356784 │
│              ┆ md          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ egrantha-ai  ┆ faded-noir  ┆ 0.5      ┆ 0.5      ┆ … ┆ 0.555556 ┆ 0.544444 ┆ 1.0      ┆ 0.0      │
│ yihao        ┆ clear-buyer ┆ 0.5      ┆ 0.75     ┆ … ┆ 0.0      ┆ 0.25     ┆ 1.0      ┆ 0.0      │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [25]:
get_results_per_run(pan26_df_filtered_best.filter(
    ((pl.col('model') == 'nytimes-writing-prompts-translated-en-heuristic_obfs') | (pl.col('model') == 'human')) &
    pl.col('source').str.starts_with('nytimes')
), drop_run_and_ds=True)

shape: (38, 10)
┌──────────────┬─────────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ team         ┆ software    ┆ roc-auc  ┆ brier    ┆ … ┆ f05u     ┆ mean     ┆ fpr      ┆ fnr      │
│ ---          ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str          ┆ str         ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═════════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ dsgt-pan-26  ┆ relaxed-cop ┆ 1.0      ┆ 0.99997  ┆ … ┆ 1.0      ┆ 0.999994 ┆ 0.0      ┆ 0.0      │
│              ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ mdok         ┆ mdok        ┆ 0.999899 ┆ 0.996646 ┆ … ┆ 0.994975 ┆ 0.996294 ┆ 0.005025 ┆ 0.005025 │
│ sst          ┆ ModernBERT- ┆ 0.999874 ┆ 0.98496  ┆ … ┆ 0.976447 ┆ 0.986271 ┆ 0.030151 ┆ 0.0      │
│              ┆ large-BNN   ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ suspiciously ┆ lead-log    ┆ 0.999293 ┆ 0.974368 ┆ … ┆ 0.980296 ┆ 0.985797 ┆ 0.025126 ┆ 0.0      │
│ -coherent    ┆             ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ plagiarism-d ┆ alternating ┆ 1.0      ┆ 0.972112 ┆ … ┆ 0.964409 ┆ 0.967807 ┆ 0.0      ┆ 0.015075 │
│ etector-com- ┆ -contingenc ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ reg2         ┆ y           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ …            ┆ …           ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ yjl          ┆ antique-imp ┆ 0.256294 ┆ 0.448123 ┆ … ┆ 0.0      ┆ 0.226311 ┆ 0.145729 ┆ 1.0      │
│              ┆ ulse        ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ team-uit-huy ┆ nice-freque ┆ 0.112131 ┆ 0.494665 ┆ … ┆ 0.0      ┆ 0.220354 ┆ 0.01005  ┆ 1.0      │
│ ygiaa        ┆ ncy         ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ nai-long-zha ┆ solid-capit ┆ 0.160274 ┆ 0.48294  ┆ … ┆ 0.0      ┆ 0.219496 ┆ 0.100503 ┆ 1.0      │
│ n-dui        ┆ al          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ nexo         ┆ skinny-pige ┆ 0.041767 ┆ 0.481702 ┆ … ┆ 0.0      ┆ 0.193732 ┆ 0.135678 ┆ 1.0      │
│              ┆ on          ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
│ uned-martine ┆ current-lin ┆ 0.006818 ┆ 0.376446 ┆ … ┆ 0.0      ┆ 0.118481 ┆ 0.592965 ┆ 1.0      │
│ z            ┆ e           ┆          ┆          ┆   ┆          ┆          ┆          ┆          │
└──────────────┴─────────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘